Attempt to fix windows build issues
Add gspawn-win64-helper-console.exe to windows build and change
windows subsystem to "windows" in meson to prevent a console window
from popping up

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -166,6 +166,9 @@ jobs:
         echo "Copying gspawn-win64-helper executable..."
         cp --verbose "${INSTALL_DIR}/bin/gspawn-win64-helper.exe" "${DEST_DIR}/bin/" 2>/dev/null || echo "Warning: gspawn-win64-helper.exe not found."
 
+        echo "Copying gspawn-win64-helper-console executable..."
+        cp --verbose "${INSTALL_DIR}/bin/gspawn-win64-helper-console.exe" "${DEST_DIR}/bin/" 2>/dev/null || echo "Warning: gspawn-win64-helper-console.exe not found."
+
         echo "Copying detected runtime DLLs to bin..."
         if [ -f "$DLL_LIST_FILE" ]; then
           while IFS= read -r dll_path; do
